### ISSUE TITLE
Luzboa wiki

### ISSUE THREAD

**Issue by pvieira84** [luuuis/hass_omie#19]
Viva, alguma possibilidade de adicionar wiki para Luzboa? Obrigado e continuação de bom trabalho

**Comment by luuuis** [comment]
@pvieira84 vê se te serve este exemplo que o Tiago Veloso partilhou em https://forum.cpha.pt/t/integracao-omie-precos-horarios-diarios-mecanismo-de-ajuste/11668/122

```
template:
  sensor:
    - name: Luzboa Daily Spot Cost
      unit_of_measurement: €/kWh
      state_class: measurement
      state: |-
        {% set PMD = state_attr(this.entity_id, 'PMD') | float(default=0) -%}
        {% set MIBEL = state_attr(this.entity_id, 'MIBEL') | float(default=0) -%}
        {% set Desvios = state_attr(this.entity_id, 'Desvios') | float(default=0) -%}
        {% set SAJ = state_attr(this.entity_id, 'SAJ') | float(default=0) -%}
        {% set PFC = ((PMD+MIBEL)/1000) + Desvios + SAJ -%}
        {% set FA = state_attr(this.entity_id, 'FA') | float(default=0) -%}
        {% set PT = state_attr(this.entity_id, 'PT') | float(default=0) -%}
        {% set CG = state_attr(this.entity_id, 'CG') | float(default=0) -%}
        {% set TEPAi = state_attr(this.entity_id, 'TEPAi') | float(default=0) -%}
        
        {{( (PFC*(1+PT))*FA+(CG)+(TEPAi) ) | round(4) }}
      attributes:
        friendly_name: "Luzboa €/kWh"
        formula: (ER*PFC*(1+PT)*FA)+(ER*CG)+(ER*TEPAi)
        PMD: "{{ state_attr('sensor.omie_spot_price_pt', 'today_average') | float(default=0) }}"
        MIBEL: "{{ state_attr('sensor.omie_adjustment_price_pt', 'today_average') | float(default=0) }}"
        Desvios: "{{ 0 | round(4) }}"
        SAJ: "{{ 0.004 | round(4) }}"
        FA: "{{ 1.02 | round(4) }}"
        PT: "{{ 0.1507 | round(4) }}"
        CG: "{{ 0.005 | round(4) }}"
        TEPAi: "{{ -0.09580 | round(4) }}"
```

**Comment by pvieira84** [comment]
@luuuis obrigado, vou usar. Um abraço

**Comment by codedmind** [comment]
Viva nao ha exemplo para o bi-horario diario e semanal?

**Comment by luuuis** [comment]
@codedmind tenta assim para aplicar a TAR correcta para vazio e fora de vazio. A única diferença está na linha `TEPAi:`.

```yaml
template:
  sensor:
    - name: Luzboa Daily Spot Cost
      unit_of_measurement: €/kWh
      state_class: measurement
      state: |-
        {% set PMD = state_attr(this.entity_id, 'PMD') | float(default=0) -%}
        {% set MIBEL = state_attr(this.entity_id, 'MIBEL') | float(default=0) -%}
        {% set Desvios = state_attr(this.entity_id, 'Desvios') | float(default=0) -%}
        {% set SAJ = state_attr(this.entity_id, 'SAJ') | float(default=0) -%}
        {% set PFC = ((PMD+MIBEL)/1000) + Desvios + SAJ -%}
        {% set FA = state_attr(this.entity_id, 'FA') | float(default=0) -%}
        {% set PT = state_attr(this.entity_id, 'PT') | float(default=0) -%}
        {% set CG = state_attr(this.entity_id, 'CG') | float(default=0) -%}
        {% set TEPAi = state_attr(this.entity_id, 'TEPAi') | float(default=0) -%}
        
        {{( (PFC*(1+PT))*FA+(CG)+(TEPAi) ) | round(4) }}
      attributes:
        friendly_name: "Luzboa €/kWh"
        formula: (ER*PFC*(1+PT)*FA)+(ER*CG)+(ER*TEPAi)
        PMD: "{{ state_attr('sensor.omie_spot_price_pt', 'today_average') | float(default=0) }}"
        MIBEL: "{{ state_attr('sensor.omie_adjustment_price_pt', 'today_average') | float(default=0) }}"
        Desvios: "{{ 0 | round(4) }}"
        SAJ: "{{ 0.004 | round(4) }}"
        FA: "{{ 1.02 | round(4) }}"
        PT: "{{ 0.1507 | round(4) }}"
        CG: "{{ 0.005 | round(4) }}"
        TEPAi: "{{ -118.5 if now().hour < 8 or now().hour > 21 else -84.2 }}"
```
