### ISSUE TITLE
Versão ApexCharts

### ISSUE THREAD

**Issue by renatose** [luuuis/hass_omie#22]
Estava a tentar colocar a funcionar o hourly chart mas não consigo.
Idealmente estaria junto do snippet, talvez até em comentário no próprio snippet, em que versão da integração e do ApexCharts foi testado.
Se comentar o data_generator funciona, mas só com valores passados dado que não estará a ir ao atributo.

Tenho ApexCharts 2.0.4 e OMIE 1.0.0

Isto parece um pedido de suporte, mas não sabendo se foi testado com a mesma versão que eu posso não ser o único com o problema.

**Comment by luuuis** [comment]
Viva, os gráficos correm em 2.0.4 e 2.0.2 e várias versões mais antigas. Também não terá havido nenhuma alteração de relevo no `data_generator` entre essas versões. Estás a usar os novos gráficos que já usam o atributo `today_hours`?

Qual é o gráfico problemático e qual o erro que dá na consola do browser? Pode ser que eu tenha cometido algum erro ao transcrever o YAML para o Wiki.

**Comment by renatose** [comment]
Só este que que tem data generator:
https://github.com/luuuis/hass_omie/wiki/ApexChartsTodayHourlyValues
`data_generator: >
    return entity.attributes.day_hours.map((price, hour) => [ new Date(new Date().setHours(hour, 0, 0, 0)), price ])
`
E mesmo corrigindo 'day_hours' para 'today_hours' 
tendo este erro no Chrome:
`TypeError: entity.attributes.today_hours.map is not a function in 'return entity.attributes.today_hours.map((price, hour) => [ new Date(new Date().setHours(hour, 0, ...'
    at eval (eval at _generateData (apexcharts-card.js?hacstag=331701152204:835:42497), <anonymous>:3:52)`

**Comment by renatose** [comment]
Bem, esse também não funcionou, mas encontrei o teu gist na CPHA que me levou na direção certa:
`  data_generator: >
      return ((hs) => Object.keys(hs).map((dt) => [ new Date(dt), hs[dt]
      ]))(entity.attributes.today_hours)`
com este data_generator na wiki pode-se fechar o issue 👍

**Comment by JeffersM1** [comment]
É possível adicionar um título ao gráfico apex?

**Comment by JeffersM1** [comment]
@luuuis Estou a ter um problema semelhante ao de @renatose com um gráfico Apex que não carrega.  Estou a tentar criar um gráfico da lista de preços dos atributos tomorrow_hours.  Trata-se de um duplicado do gráfico Apex today_hours, em que substituí today_hours por tomorrow_hours no script yaml.  Tanto o today_hours como o tomorrow_hours são produzidos a partir do mesmo sensor.  O gráfico today_hours do Apex funciona sem qualquer problema e o gráfico tem o seguinte aspeto:
![image](https://github.com/luuuis/hass_omie/assets/97175692/c3f4df57-4a34-4936-af8f-2d08c2bc54f6)

Este é o código yaml para o cartão:
```
type: custom:apexcharts-card
update_interval: 30m
now:
  show: true
span:
  start: day
graph_span: 1d
series:
  - entity: sensor.coopernico_base_tarifario_tri_horario
    name: Coopernico Tri Horario
    stroke_width: 1
    type: line
    curve: stepline
    group_by:
      func: avg
      duration: 30m
    show:
      extremas: true
      legend_value: false
    data_generator: >
      return Object.entries(entity.attributes.tomorrow_hours).map(([dateString,
      price]) => [ new Date(dateString), price ])
yaxis:
  - id: price
    align_to: 10
```
Este é o aspeto da lista de atributos:
![image](https://github.com/luuuis/hass_omie/assets/97175692/5c9ca70e-2a31-4751-9a03-d97d47e1c441)
 
Este é o aspeto do gráfico Apex today_hours:
![image](https://github.com/luuuis/hass_omie/assets/97175692/aa6a476a-1544-4c88-945f-6ae719976825)

O que é que me está a escapar?
