### ISSUE TITLE
Gráfico Apex não está a carregar com a lista de atributos tomorrow_hours

### ISSUE THREAD

**Issue by JeffersM1** [luuuis/hass_omie#41]
@luuuis Estou a ter um problema com um gráfico Apex que não carrega.  Estou a tentar utilizar este gráfico ApexChart:https://github.com/luuuis/hass_omie/wiki/ApexChartsTodayHourlyValues

Também tentei utilizar os dois geradores de dados do exemplo emhttps://github.com/luuuis/hass_omie/wiki/ApexChartsYesterdayTodayTomorrow mas continua a ser o mesmo

```
data_generator: >
          return ((hs) => Object.keys(hs).map((dt) => [ new Date(dt), hs[dt]
          ]))(entity.attributes.tomorrow_hours)
```
e
```
data_generator: |
          return ((hours) => {
            return Object.keys(hours)
                         .map((dateString) => [ new Date(dateString), hours[dateString]])
                         .map(([date, price]) => [ date, (date.getHours() > 6 && date.getHours() < 21) ? price : null])
          })(entity.attributes.tomorrow_hours)
```

Estou a tentar criar uma tabela de preços com os atributos tomorrow_hours. Trata-se de um duplicado do gráfico Apex today_hours, em que substituí today_hours por tomorrow_hours no script yaml. Tanto o today_hours como o tomorrow_hours são produzidos a partir do mesmo sensor. O gráfico today_hours do Apex funciona sem qualquer problema e o gráfico tem o seguinte aspeto: 
![image](https://github.com/luuuis/hass_omie/assets/97175692/c3f4df57-4a34-4936-af8f-2d08c2bc54f6)

Este é o código yaml para o cartão:
```
type: custom:apexcharts-card
update_interval: 30m
now:
  show: true
span:
  start: day
graph_span: 1d
series:
  - entity: sensor.coopernico_base_tarifario_tri_horario
    name: Coopernico Tri Horario
    stroke_width: 1
    type: line
    curve: stepline
    group_by:
      func: avg
      duration: 30m
    show:
      extremas: true
      legend_value: false
    data_generator: >
      return Object.entries(entity.attributes.tomorrow_hours).map(([dateString,
      price]) => [ new Date(dateString), price ])
yaxis:
  - id: price
    align_to: 10
```
Este é o aspeto da lista de atributos:
![image](https://github.com/luuuis/hass_omie/assets/97175692/5c9ca70e-2a31-4751-9a03-d97d47e1c441)

Este é o aspeto do gráfico Apex today_hours:
![image](https://github.com/luuuis/hass_omie/assets/97175692/aa6a476a-1544-4c88-945f-6ae719976825)

O que é que me está a escapar?

**Comment by luuuis** [comment]
> O que é que me está a escapar?

Estás a visualizar o gráfico do dia hoje o qual alimentaste com dados que dizem respeito a amanhã. 🙃

Vê bem a configuração `span` dos vários gráficos: [ApexChartsYesterdayTodayTomorrow](https://github.com/luuuis/hass_omie/wiki/ApexChartsYesterdayTodayTomorrow).

**Comment by JeffersM1** [comment]
Tive de efetuar uma pequena alteração para que o gráfico Apex de tomorrow funcionasse:
antes:
```
span:
  start: day
```

agora:
```
span:
  start: day
  offset: +1d
```

![image](https://github.com/luuuis/hass_omie/assets/97175692/ac4b7a7f-321b-473f-876a-6f59a9120683)

Agora só preciso de descobrir como escalar o preço no gráfico em vez de o fazer no modelo de tarifa.
```
series:
  - entity: sensor.coopernico_base_tarifario_tri_horario
    name: Coopernico Tri Horario
    unit: €/kWh
    float_precision: 5
    transform: return x / 1000; # Pensei que esta linha iria escalar o preço do sensor
    stroke_width: 2
    type: line
    curve: stepline
    group_by:
      func: avg
      duration: 30m
    show:
      extremas: true
      legend_value: false
    data_generator: >
      return Object.entries(entity.attributes.today_hours).map(([dateString,
      price]) => [ new Date(dateString), price ])
```
