### ISSUE TITLE
A integração não está a receber o MIBEL

### ISSUE THREAD

**Issue by JeffersM1** [luuuis/hass_omie#46]
![image](https://github.com/luuuis/hass_omie/assets/97175692/dcd6152f-fc11-4ad4-ab80-6ac14a74d3e4)

Isto é um problema no sítio da OMIE?

Este é o URL correto para confirmar se o sítio do OMIE está a publicar os valores do MIBEL?https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_MAJ_EV_H_01_01_2024_01_01_2024.TXT

**Comment by JeffersM1** [comment]
Estou a utilizar a versão 1.0.2 da integração.

**Comment by jsantosdias** [comment]
Eu tenho o mesmo problema, e sem isso fico sem valores finais de preço...

**Comment by JeffersM1** [comment]
Para já, substituí todas as instâncias de "+ MAJ +" por "+ 0 +"

**Comment by luuuis** [comment]
Não sei até que ponto o mecanismo de ajuste ainda vigora. De qualquer forma actualizei os templates da Coopérnico para prescindirem desse valor caso ele não esteja disponível.

**Comment by JFRosado** [comment]
Eu ainda vejo o MAJ no template da Coopérnico. Ajustei as minhas fórmulas no meu HA e removi tudo o que tinha a ver com o MAJ. A mim já me dá valores.

**Comment by JeffersM1** [comment]
Penso que, nesta parte do código, precisamos de testar se "MAJ" tem um valor não numérico.  E, se for não numérico, utilizar "0" em vez de "MAJ".  Mas não sei como o fazer.
```
{%- if PM == None or MAJ == None %}
          {%- set price=PM %}
        {%- else %}
          {%- set price = ((PM + CGS + k)*(1.0 + FP) + MAJ + TAR) | round(2) %}
        {%- endif %}
        {%- set hh = (as_timestamp(h, None) + half_hour * 1800) | as_datetime() -%}      
        {%- if PM != None %}
          {%- set ns.hourly_data=ns.hourly_data + [(hh.isoformat(), price)] %}
        {%- endif %} 
```

**Comment by JeffersM1** [comment]
Obrigado pela atualização.  Tive de o fazer de uma forma ligeiramente diferente, talvez porque as entradas do meu dicionário são de meia em meia hora para corresponder às TARs do Tri Horário, algumas das quais mudam em intervalos de meia hora.  Seria possível incluir o meu modelo Tri Horário no vosso repositório?  E também os gráficos Apex, uma vez que também são de meia hora.

**Comment by jsantosdias** [comment]
@luuuis, muito obrigado por todo o apoio e pela qualidade desse apoio!

**Comment by JeffersM1** [comment]
@luuuis Obrigado pela atualização. Tive de o fazer de uma forma ligeiramente diferente, talvez porque as entradas do meu dicionário são de meia em meia hora para corresponder às TARs do Tri Horário, algumas das quais mudam em intervalos de meia hora. Seria possível incluir o meu modelo Tri Horário no vosso repositório? E também os gráficos Apex, uma vez que também são de meia hora.

**Comment by JeffersM1** [comment]
Este é o modelo para a tarifa tri-horária:
```
template:

  - binary_sensor:
  
      #sensor to identify if daylight savings for selecting summer or winter tariff structure
      - name: "Is DST"
        unique_id: "is_dst"
        state: "{{ now().timetuple().tm_isdst == true }}"

  - sensor:
  
      - name: "Coopérnico Base (tarifário tri-horário)"
        unique_id: coopernico_spot_price_trihorario
        unit_of_measurement: "€/MWh"
        availability: "{{ has_value('sensor.omie_spot_price_pt') }}"
        state_class: measurement
        state: >
          {%- set PM = states('sensor.omie_spot_price_pt')|float -%}
          {% set MAJ = states('sensor.omie_adjustment_price_pt')|float(0) -%}
          {% set CGS = 4.0 -%}
          {% set k = 10.0 -%}
          {% set FP = 0.15 -%}
          {% set TAR_vazio = -34.9 if now().date().isoformat() < '2024-01-01' else 9.2 -%}
          {% set TAR_ponta = 81.1 if now().date().isoformat() < '2024-01-01' else 151.1 -%}
          {% set TAR_cheias = -23.2 if now().date().isoformat() < '2024-01-01' else 23.7 -%}
                  
          {%- set t = now().hour + (now().minute/60.0 + now().second/3600 ) | round(5) %}
          {%- if t < 8.0 or t >= 22.0 %}
              {%- set TAR = TAR_vazio %}
          {%- else %}       
            {%- if states('binary_sensor.is_dst') == "off" %}
              {%- set TAR = TAR_ponta if (t >= 9.0 and t < 10.5) or (t >= 18.0 and t < 20.5) else TAR_cheias -%}
            {%- else %}   
              {%- set TAR = TAR_ponta if (t >= 10.5 and t < 13.0) or (t >= 19.5 and t < 21.0) else TAR_cheias -%}        
            {%- endif %}
          {%- endif %}
          {{ ((PM + CGS + k)*(1.0 + FP) + MAJ + TAR) | round(2) }}

        attributes:
          friendly_name: "Coopérnico Base (tarifário tri-horário)"
          formula: "(PM+CGS+K)*(1+FP)+MIBEL+TAR"
          PM: "{{ states('sensor.omie_spot_price_pt')|float }}"
          MIBEL: "{{ states('sensor.omie_adjustment_price_pt')|float(None) }}"
          CGS: "{{ 4.0 | float }}"
          k: "{{ 10.0 | float}}"
          FP: "{{ 0.15 | float  }}"
          TAR_vazio: "{{ -34.9 if now().date().isoformat() < '2024-01-01' else 9.2 | float }}"
          TAR_ponta: "{{ 81.1 if now().date().isoformat() < '2024-01-01' else 151.1 | float }}"
          TAR_cheias: "{{ -23.2 if now().date().isoformat() < '2024-01-01' else 23.7 | float }}"
          TAR: "{{ TAR | float }}"

          today_hours: >
            {% set CGS = 4.0 -%}
            {%- set k = 10.0 -%}
            {%- set FP = 0.15 -%}
            {% set TAR_vazio = -34.9 if now().date().isoformat() < '2024-01-01' else 9.2 -%}
            {% set TAR_ponta = 81.1 if now().date().isoformat() < '2024-01-01' else 151.1 -%}
            {% set TAR_cheias = -23.2 if now().date().isoformat() < '2024-01-01' else 23.7 -%}
                  
            {%- set ns = namespace(hourly_data=[]) %}
            {%- for h, PM in state_attr('sensor.omie_spot_price_pt', 'today_hours').items() -%}
              {%- set MAJ = state_attr('sensor.omie_adjustment_price_pt', 'today_hours')[h]  -%}

              {%- for half_hour in range(0, 2) -%}
              {%- set t = h.hour  + half_hour * 0.5  -%}
                {%- if t < 8.0 or t >= 22.0 %}
                  {%- set TAR = TAR_vazio %}
                {%- else %}       
                  {%- if states('binary_sensor.is_dst') == "off" %}
                    {%- set TAR = TAR_ponta if (t >= 9.0 and t < 10.5) or (t >= 18.0 and t < 20.5) else TAR_cheias -%}
                  {%- else %}   
                    {%- set TAR = TAR_ponta if (t >= 10.5 and t < 13.0) or (t >= 19.5 and t < 21.0) else TAR_cheias -%}        
                  {%- endif %}
                {%- endif %}              

              {%- if PM == None %}
                {%- set price=PM %}
              {%- else %}
                {%- if MAJ == Unknown %}
                  {%- set price = ((PM + CGS + k)*(1.0 + FP) + 0 + TAR) | round(2) %}
                {%- else %}
                  {%- set price = ((PM + CGS + k)*(1.0 + FP) + MAJ + TAR) | round(2) %}
                {%- endif %}          
              {%- endif %}

              {%- set hh = (as_timestamp(h, None) + half_hour * 1800) | as_datetime() -%}      
              {%- if PM != None %}
                {%- set ns.hourly_data=ns.hourly_data + [(hh.isoformat(), price)] %}
              {%- endif %}  
            {%- endfor -%}
            {%- endfor -%}
            {{ dict(ns.hourly_data) }}

          tomorrow_hours: >
            {% set CGS = 4.0 -%}
            {%- set k = 10.0 -%}
            {%- set FP = 0.15 -%}
            {% set TAR_vazio = -34.9 if now().date().isoformat() < '2023-12-31' else 9.2 -%}
            {% set TAR_ponta = 81.1 if now().date().isoformat() < '2023-12-31' else 151.1 -%}
            {% set TAR_cheias = -23.2 if now().date().isoformat() < '2023-12-31' else 23.7 -%}

            {%- set ns = namespace(hourly_data=[]) %}
            {%- for h, PM in state_attr('sensor.omie_spot_price_pt', 'tomorrow_hours').items() -%}
              {%- set MAJ = state_attr('sensor.omie_adjustment_price_pt', 'tomorrow_hours')[h] -%}
              {%- for half_hour in range(0, 2) -%}
              {%- set t = h.hour  + half_hour * 0.5 -%}

                {%- if t < 8.0 or t >= 22.0 %}
                  {%- set TAR = TAR_vazio %}
                {%- else %}       
                  {%- if states('binary_sensor.is_dst') == "off" %}
                    {%- set TAR = TAR_ponta if (t >= 9.0 and t < 10.5) or (t >= 18.0 and t < 20.5) else TAR_cheias -%}
                  {%- else %}   
                    {%- set TAR = TAR_ponta if (t >= 10.5 and t < 13.0) or (t >= 19.5 and t < 21.0) else TAR_cheias -%}        
                  {%- endif %}
                {%- endif %}  

              {%- if PM == None %}
                {%- set price=PM %}
              {%- else %}
                {%- if MAJ == Unknown %}
                  {%- set price = ((PM + CGS + k)*(1.0 + FP) + 0 + TAR) | round(2) %}
                {%- else %}
                  {%- set price = ((PM + CGS + k)*(1.0 + FP) + MAJ + TAR) | round(2) %}
                {%- endif %}          
              {%- endif %}       

              {%- set hh = (as_timestamp(h, None) + half_hour * 1800) | as_datetime() -%}     
              {%- if PM != None %}

                {%- set ns.hourly_data=ns.hourly_data + [(hh.isoformat(), price)] %}
              {%- endif %} 

              {%- set hh = (as_timestamp(h, None) + half_hour * 1800) | as_datetime() -%}     
              {%- if PM != None %}
                {%- set ns.hourly_data=ns.hourly_data + [(hh.isoformat(), price)] %}
              {%- endif %}         
              {%- endfor -%}      
            {%- endfor -%}
            {{ dict(ns.hourly_data) }}
```

Este é o gráfico do Hoje Apex:
```
type: custom:apexcharts-card
apex_config:
  chart:
    height: 400px
    foreColor: '#7B7B7B'
    zoom:
      type: xy
      enabled: true
      autoScaleYaxis: true
    toolbar:
      show: true
      autoSelected: zoom
update_interval: 30m
header:
  show: true
  title: Today's Energy Prices (€/kWh)
  standard_format: true
  show_states: true
now:
  show: true
  label: now
span:
  start: day
graph_span: 1d
series:
  - entity: sensor.coopernico_base_tarifario_tri_horario
    name: Price
    unit: €/kWh
    float_precision: 5
    stroke_width: 2
    type: line
    curve: stepline
    group_by:
      func: first
      duration: 30m
    show:
      extremas: true
      legend_value: false
      in_header: before_now
    data_generator: >
      return Object.entries(entity.attributes.today_hours).map(([dateString,
      price]) => [ new Date(dateString), price / 1000 ])
yaxis:
  - id: price
    align_to: 0.05
    decimals: 3
```
Este é o gráfico do O dia de amanhã Apex:
```
type: custom:apexcharts-card
apex_config:
  chart:
    height: 400px
    foreColor: '#7B7B7B'
    zoom:
      type: xy
      enabled: true
      autoScaleYaxis: true
    toolbar:
      show: true
      autoSelected: zoom
update_interval: 30m
header:
  show: true
  title: Tomorrow's Energy Prices (€/kWh)
  standard_format: true
span:
  start: day
  offset: +1d
graph_span: 1d
series:
  - entity: sensor.coopernico_base_tarifario_tri_horario
    name: Coopernico Tri Horario
    unit: €/kWh
    float_precision: 5
    stroke_width: 2
    type: line
    curve: stepline
    group_by:
      func: first
      duration: 30m
    show:
      extremas: true
      legend_value: false
    data_generator: >
      return Object.entries(entity.attributes.tomorrow_hours).map(([dateString,
      price]) => [ new Date(dateString), price / 1000])
yaxis:
  - id: price
    align_to: 0.05
    decimals: 3
```
